[package]
name = "raytracing"
version = "0.1.0"
authors = ["Stephen OBrien <wayofthepie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
impl_ops = "0.1.1"
